#---
- name: 清理 Jenkins 资源(有命名空间)
  ansible.builtin.shell: |
    kubectl get {{ item.kind }} -n jenkins --no-headers -o custom-columns=":metadata.name" \
    | grep -E "^{{ item.name }}" \
    | xargs --no-run-if-empty kubectl delete {{ item.kind }} -n jenkins --ignore-not-found
  loop:
    - { kind: Deployment, name: "jenkins" }
    - { kind: Pod, name: "jenkins" }
    - { kind: Service, name: "jenkins" }
    - { kind: ConfigMap, name: "jenkins-init-scripts" }
    - { kind: ConfigMap, name: "jenkins-config-yaml" }
    - { kind: PersistentVolumeClaim, name: "jenkins-pvc" }
  failed_when: false
  ignore_errors: yes
  delegate_to: localhost
  run_once: true


- name: 清理 Jenkins 资源(无命名空间)
  ansible.builtin.shell: |
    kubectl get {{ item.kind }} --no-headers -o custom-columns=":metadata.name" \
    | grep -E "^{{ item.name }}" \
    | xargs --no-run-if-empty kubectl delete {{ item.kind }} --ignore-not-found
  loop:
    - { kind: PersistentVolume, name: "jenkins-storage" }
  failed_when: false
  ignore_errors: yes
  delegate_to: localhost
  run_once: true

